width_label:
  width: 100
  height: 40
  alignment: center
  fontFamily: times
  fontPoint: 16
  text: "width"

height_label:
  width: 100
  height: 40
  alignment: center
  fontFamily: times
  fontPoint: 16
  text: "height"

button:
  width: 120
  height: 40
  fontFamily: times
  fontPoint: 14
  fontBold: False
  text: "Open Image"

img_label:
  width: 640
  height: 360
  alignment: center

